Update animate.py
deleomike/pick_and_place pull request #5
Opened 2023-04-04 11:35 UTC by saams4u

Updated this file to work directly with the controller class to produce the desired animation.

2023-04-04 22:16 UTC, deleomike commented
I'll take a look at this and the others tonight

2023-04-05 00:32 UTC, deleomike requested changes

2023-04-05 00:32 UTC, deleomike commented on assistant/ui/animate.py
> +        BaseItem(pose=SE3([0.5, 0, 0.9]))
Can you make this the Cube object?

2023-04-05 17:20 UTC, saams4u reviewed
Updated the code to include a list of cubes with the requisite properties. Note that I removed the `color` property from the Block object and replaced it with a `pos_id` instead.

2023-04-05 18:03 UTC, merged